### ISSUE TITLE
Factory mapping conflicting when not CrossContext

### ISSUE THREAD

**Issue by Barbog** [strangeioc/strangeioc#103]
I was working with some binding code which had a simple
```
injectionBinder.Bind<IModule>().To<Module>();
```
and trying to inject it (into a mediator) would cause the binder to not exit the conflicted state. Only by adding marking the binding as CrossContext was it able to work.
```
injectionBinder.Bind<IModule>().To<Module>().CrossContext();
```

This is awkward as we're only using one Context (though we're considering multiple for the sake of organization). Singleton injectionBinder bindings (Singleton, ToValue) all work fine but a simple Bind<X>().To<Y>() factory binding without a "ToName" or "CrossContext" was causing issues. I tried to follow an example in StrangeRocks but there were no examples of such a straight forward binding. 

Thoughts on what could be causing this? I'd rather not have to add CrossContext flags by default on all my factory bindings.

**Comment by fogAndWhisky** [comment]
This hasn't been responded to for nearly a year. Closing.
