### ISSUE TITLE
Question about Bindings being in a conflicted state

### ISSUE THREAD

**Issue by animepauly** [strangeioc/strangeioc#124]
Hi! I really love the framework, but one thing that I keep running into is this error(BinderException: Binder cannot fetch Bindings when the binder is in a conflicted state) when I am binding signals to commands and am passing an interface (this is NOT to say this always happens, but I notice it a lot when I do something like the following):

In my AppContext I have 

```
injectionBinder.Bind<ISurveyDataVO>().To<ParseSurveyDataVO>();
commandBinder.Bind<ShowAdSurveySignal>().To<ShowAdSurveyCommand>();
```

and from a mediator I am calling:

```
ShowAdSurveySig.Dispatch(_currentSurveyDataVO); //I ensure _currentSurveyDataVO is not null at this point
```

_currentSurveyDataVO is set by in the mediator from another command that fetches the survey

```
private void _fulfillCurrentAdSurveyHandler(ISurveyDataVO __surveyDataVO)
{
    FulfillCurrentAdSurveySig.RemoveListener(_fulfillCurrentAdSurveyHandler);
    _currentSurveyDataVO = __surveyDataVO;
}
```

My simple command where it is throwing the conflicted state. Unity is saying ISurveyDataVO is conflicted.

```
public class ShowAdSurveyCommand : Command
{
    [Inject]
    public ISurveyDataVO SurveyDataVO{get;set;}

    public override void Execute()
    {
        Debug.Log ("ShowAdSurveyCommand::Execute called..."+SurveyDataVO.SurveyLinkStr);
        Retain ();
    }
}
```

My question is how does the interface become conflicted? This has been the main thing I don't understand, I have workarounds when I run into this but I don't like them, as the framework should work this way, just not sure what I am doing wrong. Any help you can give is greatly appreciated, and if not I just want to thank you for keeping up with this great framework!

**Comment by brandesign** [comment]
Hi,
Sorry to dig up this old issue. At the moment we are having the problem that a lot of those BinderExceptions pop up. The strange thing is, it only happens on devices and we cannot reproduce it. We see those exceptions in our analytics tool.
To understand it correctly: does the order of Release() and dispatching other signals matter?

```c#
public override void Execute()
{
    Retain();
    service.doBackendStuff(response => {
        someSignal.Dispatch();
        Release();
    });
}
```

Can this conflict the binder and should we do better like this?

```c#
public override void Execute()
{
    Retain();
    service.doBackendStuff(response => {
        Release();
        someSignal.Dispatch();
    });
}
```
