### ISSUE TITLE
is it bug for crossContextBridge setting？

### ISSUE THREAD

**Issue by loverains** [strangeioc/strangeioc#132]
in crossContext.cs follow code,is it a copy and paste bug?
virtual public IBinder crossContextBridge
		{
			get
			{
				if (_crossContextBridge == null)
				{
					_crossContextBridge = injectionBinder.GetInstance<CrossContextBridge> () as IBinder;
				}
				return _crossContextBridge;
			}
			set
			{
				_crossContextDispatcher = value as IEventDispatcher;
			}
		}

**Comment by WillzZz** [comment]
Nope, it looks a little odd but check out CrossContextBridge for a good explanation on what's going on here.
