### ISSUE TITLE
Signal and event supporting at the same time?

### ISSUE THREAD

**Issue by optimisez** [strangeioc/strangeioc#137]
Will it available in new version?

**Comment by fogAndWhisky** [comment]
Honestly it wasn't a feature we were discussing. You can see the list here:
https://github.com/strangeioc/strangeioc/wiki/TODO-list-for-next-version

Generally, I tend to think projects use one or the other. I suppose if enough people tell us they need to be able to mix it up, we can consider getting that in. Can you explain why you want it?

**Comment by fogAndWhisky** [comment]
Closing, since hasn't been acted on. Feel free to reopen if you want to discuss further.
