### ISSUE TITLE
Crashes in XboxOne

### ISSUE THREAD

**Issue by Sergit** [strangeioc/strangeioc#139]
Hi everyone,
I've tested a working simple sample scene just with one context and one start signal/command with a debug log on XboxOne. It crashed in both Unity 4.3.4f1 and Unity 5. I also tried the U5 branch of the framework with no luck.

I investigated a bit putting debug logs in every single line of the context initialization sequence and I found out it crashed in the very first Bind try in CrossContext.cs line 87:

injectionBinder.Bind<IEventDispatcher>().To<EventDispatcher>().ToSingleton().ToName(ContextKeys.CROSS_CONTEXT_DISPATCHER).CrossContext();

The "injectionBinder.Bind<IEventDispatcher>()" part executes properly returning a non null binding.
"To<EventDispatcher>()" never gets executed.

Afterwards I tried using the non generic Bind/To function for this line and it executed properly.

So that brings me some questions:
Is there any known workaround for XboxOne?
Will IL2CPP fix this also on consoles when available?
Would it be possible to add a "#define ENABLE_GENERICS false" somewhere in the framework in order to exclude the generic methods?

**Comment by WillzZz** [comment]
Sadly, I don't have an xbone to test on. Fixing that problem by getting MS to send me a devkit. Until then, maybe you could ask in the google group or ask other unity xbox one devs.

I don't know of other workarounds, but it sounds like you have one. I don't know if adding an ifdef is the right answer for this. I'm having trouble googling for a general problem with generics on xbox one. Let me know if you find something. I might ping our scripting team. I don't expect il2cpp to ship for consoles soon, but then again I haven't asked so I don't know for sure.

I suppose you could try looking at stripping, also?

**Comment by prankard** [comment]
Hi Sergit,

I read this issue a couple of weeks ago.
I had similar issues when using StrangeIOC for the WebPlayer a while back. I can say, if the Console platforms get updated to a IL2CPP version, they have supported generics now so it will be fixed.

However, I build a port of Robotlegs before this issues was fixed, and the framework doesn't use generics in it's core:
https://github.com/robotlegs-sharp/robotlegs-sharp-framework

It is similar in API but very different from the core of Strange IOC, but it would be interesting to know if this API would work on consoles.

**Comment by fogAndWhisky** [comment]
@prankard

Awesome! Good luck with RL#! I'll add it to our list of DI solutions for Unity. :)

**Comment by prankard** [comment]
> Awesome! Good luck with RL#! I'll add it to our list of DI solutions for Unity. :)

Thanks :smile: I hope it does well. 
There seems to be plenty of people wanting to use good practices with StrangeIOC for Unity so I hope there is a market for it.

**Comment by fogAndWhisky** [comment]
Well, "market" may  be an elusive term in this case. Will and I write a fair bit of code, field a lot of questions, and spend a good lot of time thinking daft thoughts. The remunerations come mostly in small quantities of "thank yous" from our users, and occasional shots of whisky. Which we mostly buy each other.

**Comment by WillzZz** [comment]
Closing issue, properuser of link.xml solves this.
