### ISSUE TITLE
MVCSContext never sets reference to itself in assigned ContextView

### ISSUE THREAD

**Issue by JayJayZZ** [strangeioc/strangeioc#141]
Hi!

While we're waiting for the Strange release, I had to move forward and implement the functionality for Mediators providing OnEnabled() and OnDisabled() handlers myself. I then stumbled upon the following issue:

The ContextView has a property context which seems to never being set. 
```C#
public IContext context{get;set;}
```
https://github.com/strangeioc/strangeioc/blob/master/StrangeIoC/scripts/strange/extensions/context/impl/ContextView.cs#L44

But nevertheless, this reference is checked in View.bubbleToContext which will then always result in null:
```C#
if (contextView.context != null)
```
https://github.com/strangeioc/strangeioc/blob/master/StrangeIoC/scripts/strange/extensions/mediation/impl/View.cs#L107

In my opinion, the place to set this reference should in MVCSContext.SetContextView but this never happens:
```C#
override public IContext SetContextView(object view)
{
    contextView = (view as MonoBehaviour).gameObject;
    if (contextView == null)
    {
        throw new ContextException("MVCSContext requires a ContextView of type MonoBehaviour", ContextExceptionType.NO_CONTEXT_VIEW);
    }
    return this;
}
```
https://github.com/strangeioc/strangeioc/blob/master/StrangeIoC/scripts/strange/extensions/context/impl/MVCSContext.cs#L218

I therefore changed the function the following, View.bubbleToContext now behaves for me as expected:
```C#
override public IContext SetContextView(object view)
{
    ContextView cntxtView = view as ContextView;
    if (cntxtView == null)
    {
        throw new ContextException("MVCSContext requires a ContextView of type MonoBehaviour", ContextExceptionType.NO_CONTEXT_VIEW);
    }
    contextView = cntxtView.gameObject;
    cntxtView.context = this;
    return this;
}
```

**Comment by fogAndWhisky** [comment]
Hi @JayJayZZ!

Thanks for being an active part of the Strange community! I appreciate you pointing this out, but I believe you're mistaken. Setting the value of Context on the ContextView is the responsibility of the ContextView itself. It's part of the regular bootstrapping process of every Strange app. 

See, for example, the GameBootstrap from StrangeRocks. 

https://github.com/strangeioc/strangerocks/blob/master/StrangeRocks/Assets/scripts/strangerocks/game/GameBootstrap.cs

All the best!

**Comment by JayJayZZ** [comment]
Thanks for getting back to me so quickly @fogAndWhisky! Since we're evaluating Strange for our current project, you might see me more often in the upcoming weeks. Sorry in advance ;-)

You're right, this is the first classic mistake I made while taking my first Strange steps. I used
```C#
public class Main : ContextView
{
    void Awake()
    {
        MainContext context = new MainContext(this);
        context.Start();
    }
}
```

Thanks for clearing that up!

**Comment by JayJayZZ** [comment]
Sure! I am closing it.
