### ISSUE TITLE
How do I get sibling views to catch signals fired from a command that was triggered from another sibling?

### ISSUE THREAD

**Issue by animepauly** [strangeioc/strangeioc#149]
Hi everyone,
In my app, I have a parent view that stitches together a bunch of child views in scrollable container. One of the child views is sending a signal bound to a command and that command is firing a signal back with a value object payload. The child view that sent the signal bound to the command catches that signal as expected, but I have other sibling views that are also interested in that payload to update information for them. I thought about having the parent send the signal bound to the command and then updating the children directly, but two issues I see with that are: 

A) The signal bound to the command is also sending some info directly tied to the child view that sent it. It's sending an image from that view to be updated and a string that reflects that specific view. So the parent doesn't have that info and I would have to make that available by I guess having the child referenced in the parent and then grabbing those properties which ties into problem b...

B) Have the parent have direct references of the children, call the initial signal bound command by grabbing properties from the child view to be sent and then on the signals return I update the children directly. I am sure this will work but seems counter intuitive to Strange as I am now creating direct dependencies which is what I want to avoid. Here are some code snippets to make things more clear

```
//child view also when I add the listener to the parent, the parent catches it too
public override void OnRegister()
{
	view.init();
        FulfillAdDataVOSig.AddListener(_fulfillAdDataVOHandler);
	GetCurrentAdInfoSig.Dispatch(view.PrefabIdStr, view.PlayAdImg);
}

private void _fulfillAdDataVOHandler(IAdDataVO __adDataVO)
{
	Debug.Log ("BrandInteractionQuizResultsMediator::_fulfillAdDataVOHandler called...");
	//This is being called
}

//sibling view
public override void OnRegister()
{
	view.init();
        FulfillAdDataVOSig.AddListener(_fulfillAdDataVOHandler);
}

private void _fulfillAdDataVOHandler(IAdDataVO __adDataVO)
{
	Debug.Log ("BrandInteractionMoreFunMediator::_fulfillAdDataVOHandler called...");
	//This is NOT being called despite listening for it
}
```

**Comment by WillzZz** [comment]
I would just reference the children in the parent. That's likely what it is for. If you're finding you are combining concerns in that parent view, you can always make an intermediary object responsible for managing those children and perhaps mediating on their behalf. A parent can know about its child. A child shouldn't know about its parent. 

PS Questions like this are better suited for the [google group ](https://groups.google.com/forum/?hl=en#!forum/strangeioc)

**Comment by animepauly** [comment]
Thanks for the advice and will do in the future!
