### ISSUE TITLE
This repo gives me an error in the AbstractMediationBinder at line 104:

### ISSUE THREAD

**Issue by TokyoDan** [strangeioc/strangeioc#155]
I tried this repo on Unity 4.6.4 and it give me an error in the AbstractMediationBinder at line 104:

NullReferenceException: Object reference not set to an instance of an object
strange.extensions.mediation.impl.AbstractMediationBinder.InjectViewAndChildren (IView view) (at Assets/StrangeIoC/scripts/strange/extensions/mediation/impl/AbstractMediationBinder.cs:104)
strange.extensions.mediation.impl.AbstractMediationBinder.Trigger (MediationEvent evt, IView view) (at Assets/StrangeIoC/scripts/strange/extensions/mediation/impl/AbstractMediationBinder.cs:55)
strange.extensions.context.impl.MVCSContext.AddView (System.Object view) (at Assets/StrangeIoC/scripts/strange/extensions/context/impl/MVCSContext.cs:306)
strange.extensions.mediation.impl.View.bubbleToContext (UnityEngine.MonoBehaviour view, Boolean toAdd, Boolean finalTry) (at Assets/StrangeIoC/scripts/strange/extensions/mediation/impl/View.cs:129)
strange.extensions.mediation.impl.View.Start () (at Assets/StrangeIoC/scripts/strange/extensions/mediation/impl/View.cs:81)

**Comment by unitymarc** [comment]
Which branch are you on? The AbstractMediationBinder is still experimental, so I presume you're attempting to work from one of our development branches (i.e., something other than master)? That's great, since we need people to look at all the new work...just want to make sure your intent is to help us vet the new work, rather than try to make your own product.

Can you give me more particulars about the scenario in which you received this error?

**Comment by unitymarc** [comment]
*Note for investigation*: from the stack trace, it would appear that this in MediationBinder...

    protected override IView[] GetViews(IView view)
    {
        MonoBehaviour mono = view as MonoBehaviour;
        return mono.GetComponentsInChildren(typeof(IView), true) as IView[];
    }

...returns NULL. Can't quite see just yet how that's possible.

**Comment by TokyoDan** [comment]
I just downloaded this repo: https://github.com/strangeioc/strangeioc/tree/marc/abstract-mediation 
I just opened the project in Unity 4.6.4 and tried it with both scenes that are in that project and got that error is both cases. I made absolutely no changes nor added any assets. 

And the reason I am trying that development branch is not to make my own product now. Since I am studying StrangeIoC and a bit in over my head I am trying to keep up with the latest changes that will make it into the 1.0 release  to lessen my confusion and so I won't have to unlearn anything that becomes obsolete.

**Comment by fogAndWhisky** [comment]
Alright, cool. So long as you're doing that intentionally and understand that you're looking at work-in-progress I heartily approve. :)

On the point of obsolescence and breaking changes, I don believe there will be any *from an external perspective*. I.,e., if all you do is is use the existing  components (InjectionBinder, MediationBinder, Signals, etc) you should find that Strange 1.0 just slots into place with some fun new features. On the other hand, if you've created custom Binder subclasses, there may be things you have to do. Most

**Comment by fogAndWhisky** [comment]
Sorry. On my phone and my finger slipped. D'oh!

Most obvious of these 'subclass changes' is that we're talking about making Signals the default message bus mechanism. If we do that, there will necessarily be a small refactor required to use the new default MVCSContext.

**Comment by TokyoDan** [comment]
I am concerned because Mediators may become non-Monobehaviors so I want to be sure that my code takes that into account.

**Comment by fogAndWhisky** [comment]
Nope. That ain't changing. The reason for the abstraction in the Mediation system is to allow for other types of View Mediation. Specifically, Editor-based views.

**Comment by fogAndWhisky** [comment]
There was a casting error in MediationBinder. Fixed by commit 5c033f2.

**Comment by TokyoDan** [comment]
Glad I could help. How is this different from the main branch? Do I still use Views and Mediators the same as I would with the main repo?

**Comment by fogAndWhisky** [comment]
The differences have to do with testability and flexibility. It won't make any difference to you as a content creator. For us as developers of Strange, it allows us to test code we couldn't test previously (which, when it's ready, means fewer unexpected errors like the one you discovered).  In terms of flexibility, it means I can create new types of MediationBinders that have no relationship with MonoBehaviours. I'm working on an EditorMediationBinder — Strange 1 will allow you to build editor extensions. In the future someone might want to use Strange in a  Xamarin project. This change will make creating a Binder for that use case pretty trivial.
