### ISSUE TITLE
Next release of StrangeIoC?

### ISSUE THREAD

**Issue by rmtuckerphx** [strangeioc/strangeioc#156]
Just started using Unity and I think that StrangeIoC actually makes it easier to work with. How stable is the code on tip? When is the next official release of StrangeIoC?

Thanks.

**Comment by srimarc** [comment]
Hi @rmtuckerphx!

So glad you asked! While we haven't set a certain release date for Strange 1.0, I can qualitatively say it's "pretty close". The last two major features are code complete, but still under review, and everything needs some solid real-world testing and documentation before we can sign off and declare it fit for use. I would treat tip as good enough for vetting, but still not production-ready. 

If you look at https://github.com/strangeioc/strangeioc/wiki/TODO-list-for-next-version you'll see the latest of what is/is not on tip. Might help you decide how adventurous you care to be. :)
