### ISSUE TITLE
PriorityComparer has wrong detection of [PostConstruct] attribute

### ISSUE THREAD

**Issue by dariy** [strangeioc/strangeioc#160]
Use-case: serveral attributes on [PostConstruct]'ed method.

ReflectionBinder line 223:
```C#
		private static int GetPriority(MethodInfo methodInfo)
		{
			var attr = methodInfo.GetCustomAttributes(true)[0] as PostConstruct;
			if (attr == null)
				throw new NullReferenceException();

			return attr.priority;
		}
```

It can be more than one attribute.

Working code:

```C#
		private static int GetPriority(MethodInfo methodInfo)
		{
			var attr = methodInfo.GetCustomAttributes(true).OfType<PostConstruct>().FirstOrDefault<PostConstruct>();
			if (attr == null)
				throw new NullReferenceException();

			return attr.priority;
		}
```

or you can use First<>(). It'll throw ```InvalidOperationException``` if source sequence is empty.

```C#
		private static int GetPriority(MethodInfo methodInfo)
		{
			var attr = methodInfo.GetCustomAttributes(true).OfType<PostConstruct>().First<PostConstruct>();
			return attr.priority;
		}
```

**Comment by unitymarc** [comment]
Sorry for the delay in getting back. We've been snowed under by an event in Spain. There hasn't been much time for sleep, let alone anything else.

We have a fix for this issue for the upcoming release of v1.0. If you want our version, you can:

    git cherry-pick a382635c47de6fa56f9eb64f35495116e8f59218

https://github.com/strangeioc/strangeioc/commit/a382635c47de6fa56f9eb64f35495116e8f59218
