### ISSUE TITLE
ContextView doesn't invoke OnRemove on self mediator

### ISSUE THREAD

**Issue by anmelegov** [strangeioc/strangeioc#161]
Please add to documentation that i will call context.RemoveView(...) manually from ContextView or fix this if this is a bug

**Comment by fogAndWhisky** [comment]
I'll make sure we document this better in the upcoming revision to The Big, Strange How-To. Note though that this is a fundamental misunderstanding of what the ContextView is for. It's not a View like the one that manages some UI or a Player GO. It doesn't extend View and isn't meant to be mediated. It's simply a container for the entire Context. When it goes away, so does the Context, and (if you use the structure we recommend) all the Views and models etc within that Context. 

If for some reason you find you absolutely have to Mediate a ContextView, your solution to call it manually is the correct one. But I'd ask myself first why this was necessary.
