### ISSUE TITLE
Signals: Mediator listeners may trigger before associated Commands are executed

### ISSUE THREAD

**Issue by jayallanjethwa** [strangeioc/strangeioc#162]
Hi!

Since Strange's Signal implementation does not support and/or use priorities, it may happen that, if a Mediator listens to a signal which is also bound to a Command, the Mediator's listener triggers before the Command has executed.

Here is an example setup:

MyContext
```c#
injectionBinder.Bind<MySignal>().ToSingleton();
commandBinder.Bind<MySignal>().To<MyCommand>();
mediationBinder.Bind<MyView>().To<MyMediator>();
injectionBinder.Bind<MyModel>().ToSingleton();
```

MyMediator
```c#
[Inject]
public MyView View { get; set }
[Inject]
public MySignal MySignal { get; set; }
[Inject]
public MyModel MyModel { get; set; }

void OnRegister()
{
    MySignal.AddListener(DoSomething);
}

void DoSomething()
{
    var data = MyModel.GetData(foo);
    View.Update(data);
}
```

MyCommand
```c#
[Inject]
public DataFromSignal DataFromSignal { get; set; }
[Inject]
public MyModel MyModel { get; set; }

override public void OnExecute()
{
    MyModel.SetData(DataFromSignal);
}
```

As far as I see it, the only workaround to prevent this is to create another signal which is dispatched by MyCommand after it has updated MyModel. The Mediator then listens for this new signal instead of MySignal to assure that MyModel has been updated.

From my point of view, Commands that are bound to a signal should always trigger before listeners of a Mediator are notified. Is this correct or am I overthinking this? 

Thanks!

**Comment by WillzZz** [comment]
It's not quite this simple. It's just a simple race condition with the way you've written your code. You can (temporarily, within the current implementation of c# events) guarantee ordering of events, but that's not a smart practice within an application, by my estimation. In simple cases it's fine, but complex race conditions arise easily.

Command Binder isn't doing anything special, in ResolveBinding we're adding a listener just like any other signal. Signal ordering is utilizing event ordering in C#, so we play by the same exact rules. I'm not sure I could figure out how to make one act before another if I tried. The ordering of events is an implementation detail that you shouldn't rely on. It's unlikely to change, but it's not worth the headache if it does.

The good news is this is a common problem, and the solution is pretty easy. We're going to do this like math class and teach the slower way, and then the better way.

The slower way is to add a signal (or signals, depending on your needs) to your model to alert the outside world when it updates. Anyone can listen to that signal, and in the setter you'll set the value and then dispatch the signal. Anything listening will receive the updated payload, and they do as they please.

The better way involves a simple gist I wrote https://gist.github.com/WillzZz/e188d3f42a9b87b20716 which allows you to remove the boilerplate of this common operation. Wrap a value in Bindable<> and listen to OnUpdated and set the value normally. Easy peasy.

**Comment by jayallanjethwa** [comment]
Thanks for the quick reply :-)

Basically the ordering of events would be possible by overriding the add and remove methods with our own behaviour, so that the listeners are added and triggered by prority. This would then allow the implementation of something similar to the PrioritySignal from AS3Signals.

You make a good point that signal/event orders should not be relied upon. Still, I'd expect that Commands are proritized over Mediators because a Mediator should never contain any business logic and merely reacts. But this might be merely a personal feel.

Thanks for the Bindable<> gist, this looks like a neat tool. I have changed our code to reflect the consideration that event orders are not reliable and have now got rid of the racetime conditions.

**Comment by WillzZz** [comment]
Writing our own implementation would be far too slow. It's totally possible, but it would be unusable.

**Comment by jayallanjethwa** [comment]
OK. This issue can be closed then. Thanks for the help!
