### ISSUE TITLE
Add meagre enhancement in ImplicitBinder

### ISSUE THREAD

**Issue by AmanAgnihotri** [strangeioc/strangeioc#170]
Since the v1.0 for Strange will be releasing soon, I thought to mention the following:

#### Params

The current method signature for `ScanForAnnotatedClasses` in `ImplicitBinder` is:

```c#
void ScanForAnnotatedClasses (string[] usingNamespaces);
```

As a user of StrangeIoC, many a times, I just have the need to scan through one particular namespace.

Adding `params` to this method signature will make that type of code look more elegant.

Here's how the method's signature will then look like:

```c#
void ScanForAnnotatedClasses (params string[] usingNamespaces);
```

And then users can call it in following ways:

```c#
implicitBinder.ScanForAnnotatedClass ("Some.Namespace");
implicitBinder.ScanForAnnotatedClass ("Some.Namespace", "Other.Namespace");
implicitBinder.ScanForAnnotatedClass (new string[] { "Some.Namespace" });
```

___

#### Different Assembly Scanning

I also tend to keep **StrangeIoC** code in the **Assets/Plugins** folder for my projects, most times in the form of DLL but even with the code present, I realised that the implicit binder failed to bind the right classes together because the assembly for my scripts and the assembly for Strange were different due to the location differences.

My solution for that was to overload the `ScanForAnnotatedClasses` method and supply the `Assembly` to it via that.

Those signatures were:
```c#
void ScanForAnnotatedClasses (params string[] usingNamespaces);

void ScanForAnnotatedClasses (Assembly assembly, params string[] usingNamespaces);
```

I see that in `fix/implicit-binding-from-dll` branch the once private `assembly` field has now become a public property, making the assembly changes possible. And that is why I didn't create any pull request for the meagre `params` enhancement request.

**Comment by WillzZz** [comment]
Sure make a PR (to tip) for the params change and write a couple tests to cover it. The latter we have on tip. Thanks! Sorry this slipped through the cracks. My time is showing up in big chunks and then disappearing suddenly, just like me :)

**Comment by fogAndWhisky** [comment]
Work on this has been merged. Closing.
