### ISSUE TITLE
Requesting clarification the bool argument in Context(view,automapping)

### ISSUE THREAD

**Issue by mohaider** [strangeioc/strangeioc#171]
Hello there! 
I was wondering if you could clarify the use of the boolean argument in the Context(view, automapping) constructor found in the class strange.extensions.context.impl.Context. I thought setting it to true would automatically map bindings but after digging in to the code, that is not the case, mapping is set to MANUAL_MAPPING.  I would appreciate any feedback on this as I'm really digging this framework.

**Comment by fogAndWhisky** [comment]
The Boolean form hails from an earlier time, retained for backwards compatibility. It is one form of Context startup that allows you to suspend the process mid-way through. The versions we intend you to use these days  are either the basic form:

    public Context (object view)

...which is entirely automatic. Everything will bootstrap and the START event (or Signal) will fire.

Or else the ContextStartupFlags version:

    public Context (object view, ContextStartupFlags flags)

The flags give you the most precise control over each stage of Context bootstrapping, and are a bit more future-proof. The flags are detailed here: https://github.com/strangeioc/strangeioc/blob/master/StrangeIoC/scripts/strange/extensions/context/api/ContextStartupFlags.cs

Now, the Boolean form to which your refer:

    public Context (object view, bool autoMapping)

...if True, will suspend before the Start() method is called. If you choose this form, you won't get any Strange bindings...not even the core components...until you call Start() manually. If you use this method with False, you also will need to call Start() manually, but *in addition* you will need to call Launch() manually. These suspensions allow you to wait until something happens (for example, a file loads) before continuing with the bootstrapping process.

**Comment by mohaider** [comment]
Thank you for your prompt reply, I was a bit confused after the method wasn't behaving, assuming that "bool autoMapping" would automap all bindings

**Comment by unitymarc** [comment]
Yeah, I agree that the naming is probably a little misleading. In that original form we *always* assumed that you'd create the Context and then call Start(). Thus "autoMapping" referred to a different part of the process. We eventually realized that this was kinda dumb and introduced the flags form along with a form that allowed you to do everything in a single line.
