### ISSUE TITLE
unusual crash in command..ctor

### ISSUE THREAD

**Issue by CoreyTrevor** [strangeioc/strangeioc#173]
Hi, 

I'm getting the following issue with strange. It's a low repro rate and it only seems to happen on iOS. I can execute the same code in the editor and it doesn't have any issues. I'm able to get the callstack and it looks like

    Game.MyCustomCommand..ctor	
    strange.extensions.command.impl.SignalCommandBinder.invokeCommand	
    strange.extensions.command.impl.CommandBinder.next	
    strange.extensions.command.impl.CommandBinder.ReactTo	
    strange.extensions.signal.impl.BaseSignal.Dispatch	
    ConsoleProRemoteServer.HandleRequest	
    strange.extensions.command.impl.SignalCommandBinder.invokeCommand	
    strange.extensions.command.impl.CommandBinder.next	
    strange.extensions.command.impl.CommandBinder.ReactTo	
    strange.extensions.signal.impl.BaseSignal.Dispatch

I'm fairly sure that the ConsoleProRemoteServer is a red herring. 

Looking at the code for invokeCommand I would say that either binding or signal is null, but I don't see how that can really be the case.

    protected override ICommand invokeCommand(Type cmd, ICommandBinding binding, object data, int depth)
		{
			IBaseSignal signal = (IBaseSignal)binding.key;
			ICommand command = createCommandForSignal(cmd, data, signal.GetTypes()); //Special signal-only command creation
			command.sequenceId = depth;
			trackCommand(command, binding);
			executeCommand(command);
			return command;
		}

I do see some issues already posted here or elsewhere that are in the constructor (ctor) but I don't think they are really the same issue. I'm open to all suggestions

**Comment by unitymarc** [comment]
Quick question on this: do you have any code in your Command's ctor?

**Comment by CoreyTrevor** [comment]
Nope, I should mentioned that in original post.
It's just the default constructor supplied by the compiler that it's using

**Comment by unitymarc** [comment]
OK. Odd...obviously this shouldn't happen. When you say 'crash', do you mean the app fails entirely? Is it possible that something you're doing is leading to an infinite loop? I.e., perhaps a race condition only manifests itself on iOS, and this leads to a signal triggering another signal which loops back on the original signal (possibly even a loop of several signals)? If we're talking about something that actually crashes an app, that's about all I can think of at the moment that would account for this.

**Comment by CoreyTrevor** [comment]
It's actually an NRE

    Info: NullReferenceException: A null value was found where an object instance was required.

    Exception Type: unknown

It's really unusual. What you mention does seem plausible though.

**Comment by unitymarc** [comment]
Don't know if I have anything to offer if you're getting an NRE. That sounds like it has to be in your code somewhere (essentially because if this was an issue in Strange, we'd know about it by now). If you think it's on us, and can think of anything that might help us identify it, I'm happy to consider further.

**Comment by fogAndWhisky** [comment]
Gone stale without response. Please re-open if still relevant.
