### ISSUE TITLE
ClickDetector of ShipView in multiplecontexts example doesn't work

### ISSUE THREAD

**Issue by HoMeBoYErik** [strangeioc/strangeioc#180]
I'm testing the multiplecontexts example with Unity 5.1.3 and at runtime I receive a Null reference.
It seems that in the ShipView when adding the ClickDetector component during Init(), it fails to find the clicker dispatcher. Debugging I see that in this code:

    internal void init()
    {
        gameObject.AddComponent<ClickDetector>();
        ClickDetector clicker = gameObject.GetComponent<ClickDetector>();
        clicker.dispatcher.AddListener(ClickDetector.CLICK, onClick);
    }

 the clicker.dispatcher is null

Any help?

**Comment by fogAndWhisky** [comment]
Thanks for the report. You're seeing this on master? On tip?

**Comment by HoMeBoYErik** [comment]
I see this on master from github (downloaded he zip). I also tested with unity 4.6.8 and the same occurs.

**Comment by HoMeBoYErik** [comment]
I cloned the 1.0f2 from github and the example scene works correctly now.

**Comment by unitymarc** [comment]
Cool. Can we mark this as resolved?

**Comment by HoMeBoYErik** [comment]
I still don't understand the problem with 0.7 but Yes, thank you. I will develop with 1.0f2 until the new version will be available on Asset Store. Thank you

**Comment by DarkChowder** [comment]
Let me list some major problems with the asset in the asset store:
The link in the readme, and the link on the asset are dead links
The asset is not the current unity version
The asset does not work with the current version of unity

Most people will then assume the project is dead.
I would of assumed that too, if I didn't google Strange IOC, and find this github repository.

This has probably killed most, if not all traffic you would be receiving from the asset store. The only thing you have to do to fix it, is to update it with a small patch fixing the listed issues.

**Comment by fogAndWhisky** [comment]
Cool. Thanks again for the report. Closing.
