### ISSUE TITLE
Update commands to support strongly typed signal data

### ISSUE THREAD

**Issue by dshook** [strangeioc/strangeioc#182]
It would be amazing if you could put in the signal data parameters into the Execute functions of commands just like if you add an event listener.

As far as I can see right now you have to do some nasty casting to get the signal data in a command
```c#
            var dataArray = (object[])data;
            var id = (int)dataArray[0];
            var key  = dataArray[1] as SocketKey;
```

Which defeats the point of the strongly typed signal.

**Comment by WillzZz** [comment]
Just inject those properties! Easy peasy.

**Comment by dshook** [comment]
Can you give an example of what you mean?

The data that I'm including on the signals won't be bound to anything that's injected.  For example, if I have a playerMove signal and the data is a Coordinate object, that coordinate won't be bound to anything to inject.

**Comment by unitymarc** [comment]
Commands understand the principle of injection, and everything in a Signal's payload is injectable into its bound Commands. 

Thus a Signal with a payload Coordinate can be injected as Will describes. 

    [Inject]
    public Coordinate coord { get; set; }

    override public void Execute() {
        //coord is available here
    }

**Comment by dshook** [comment]
Nice, thanks for the quick response.

Might I suggest making it a bit more clear in the documentation that this is going on?

Thanks again for the lib.
