### ISSUE TITLE
Multiple Command instances in sequence not firing properly

### ISSUE THREAD

**Issue by deimors** [strangeioc/strangeioc#183]
Multiple instances of the same Command bound in sequence are not all firing.

ie: 

    commandBinder.Bind<Signal>().To<A>().To<B>().To<B>().To<A>().InSequence();

Expecting command execution sequence "A; B; B; A" when Signal fires, but only "A; B" executes.

**Comment by fogAndWhisky** [comment]
Thanks for the report. I'll investigate.

**Comment by fogAndWhisky** [comment]
Confirmed. But it appears to be even simpler: CommandBinders (both Event and Signal) do not support firing the same Command more than once. Neither Signals nor Sequences are specifically involved. Investigating what it might take to fix.

**Comment by fogAndWhisky** [comment]
So I have a fix, but I want to confirm it with @WillzZz before pushing. In the meantime, try this out and see if it does what you need.

In CommandBinding, make the following changes:

    public CommandBinding() : base()
    {
        _value.uniqueValues = false;    //New line
    }

    public CommandBinding (Binder.BindingResolver resolver) : base(resolver)
    {
        _value.uniqueValues = false;    //New line
    }

That seems to survive all unit tests and solves the issue when I test. Just want to make sure there aren't pitfalls I haven't thought of.

**Comment by deimors** [comment]
Looks to be working well with my test code. Thanks!
