### ISSUE TITLE
Factory support in IInjectionBinding

### ISSUE THREAD

**Issue by mariuszjamro** [strangeioc/strangeioc#185]
Hi.

What do you think about adding additonal methods to `IInjectionBinding` which would allow for a factory method-like instantiation of objects:

	public IInjectionBinding ToFactory(IFactory<T> o);
	public IInjectionBinding ToFactoryMethod(Func<T> o);

The interface:

	interface IFactory<T>{
			public T Create()
	}

That would enable customization of the creation of objects before injecting them by providing custom factory.

      Bind<Spaceship>().ToFactory(new SpaceshipFactory());

 I can provide pull request with sample implementation if you'll decide that it's a good idea.

**Comment by fogAndWhisky** [comment]
Hey @mariuszjamro, thanks for reaching out!

So I'm honestly not quite sure what you're trying to accomplish here. Strange already has a factory binding:

    Bind<ISpaceship>().To<Spaceship>();

Which instantiates a new instance whenever the injection is requested. Is the idea that you want to be able to customize each instance with injectable construction parameters? We can do that, too, using Commands as our Factories:

    [Inject]
    public IInjectionBinder injectionBinder { get; set; }
    
    override public void Execute() {
        injectionBInder.Bind<int>().ToValue(42);  //Sample value
        injectionBinder.Bind<GameObject>().ToValue(MyGameObject); //Another sample value
        var mySpaceship = injectionBinder.GetInstance<ISpaceship>(); //Get the instance
        injectionBInder.Unbind<int>(); //Unbind things
        injectionBInder.Unbind<GameObject>();
        
        //At this point I'd probably apply the mySpaceship instance somehow, or,
        //more likely, send it off in a Signal to do whatever it's supposed to do.
    }

Alternatively, I guess you could forego the mappings entirely and just do this in a Command:

    override public void Execute() {
        var mySpaceShip = new Spaceship(42, someGameObject);
        //Now do something with the instance.
    }

Obviously, that latter option isn't very "Strange", but as long as you narrowly define where the constructors live, you're not really doing a lot of harm. I'd go with the first option, personally.

Are you describing some other use case I'm not understanding?

**Comment by mariuszjamro** [comment]
@fogAndWhisky I don't like the solution with Commands used as Factories, as you need to use IInjectionBinder directly and have to call Bind/Unbind manually on it. With the factory approach everything would be clearly separated and you would have all the `Bind()` calls in one place in your Context.

I was thinking about two particular applications. First one is customization of the the created object (like randomizing them):

    class Spaceship{
        public double Speed = 1.0f;
        
    }

    public class SpaceshipFactory : IFactory<Spaceship>{

        public Spaceship Create(){
            Spaceship ship = new Spaceship();
            
            ship.Speed =  new Random().NextDouble();
            return ship;
        }
    }

Another use case can be instantiation from resources/prefabs:

    public class SpaceshipGameObjectFromPrefabFactory : MonoBehaviour, IFactory<GameObject>{

        // Properties assignable/editable in the Editor gui
        public GameObject spaceShipPrefab;
        public GameObject spaceShipParent;
        
        
        public GameObject Create(){
            GameObject ship = Instantiate<GameObject>(spaceShipPrefab);
 
            // Possibly do something with the GameObject. like:
            ship.SetParent(spaceShipParent)
            
            return ship;
        }
    }

    public class SpaceshipGameObjectFromResourceFactory : MonoBehaviour, IFactory<GameObject>{

        public string spaceShipPrefabResourceName;
        
        public GameObject Create(){
            GameObject ship = Instantiate<GameObject>(Resources.Load(spaceShipPrefabResourceName));
            return ship;
        }
    }

**Comment by fogAndWhisky** [comment]
Yeah, ok, I see where you're going now. You're right that's a better approach than what I suggested, but again, I _think_ we already have a mechanism that suits the use case you want: Pools.

https://strangeioc.wordpress.com/2013/12/18/pools-at-last/

In the typical use case:

    injectionBinder.Bind<IStarship>().To<Starship>();
    pool = new Pool<Starship> ();
    pool.instanceProvider = new StarshipProvider();
    injectionBinder.Bind(pool).To<Pool<IStarship>>().ToSingleton();

`StarshipProvider` uses a `T GetInstance()` method to do what `Create()` would do in your example.

We couldn't extend from MonoBehaviour in the way your approach allows, but then we can inject a MB, so the result would be the same.

As for elegance, your binding ends up as a single line, so it's more elegant than ours is at present. Perhaps, though, we could simply massage the interface a bit like so:

    injectionBinder.Bind<IStarship>().To<Starship>().ToPool(new StarshipProvider());

I'd have thought that if we could do that, it would satisfy everything you're suggesting? What do you think?

**Comment by mariuszjamro** [comment]
This pool apreach is exactly what i was thinking about. I have never used pools in strange, so it slipped my mind that they can be used to do that. Thanks

**Comment by unitymarc** [comment]
Awesome! Sorry, should have thought of that first!
