### ISSUE TITLE
Signal dispatching won't work

### ISSUE THREAD

**Issue by seanachie69** [strangeioc/strangeioc#187]
When I try to .Dispatch() a signal, I can only get it to work in one very specific circumstance. I am testing using strangeioc's example "signalsproject" code, which I have migrated into my own app.

Within ExampleService I have injected my own signal, networkConnectedSignal. When Request() is called, this works and a mediator that listens for the signal gets it:
                
                public void Request(string url)
		{
			this.url = url;
			
			MonoBehaviour root = contextView.GetComponent<GameRoot>();
			root.StartCoroutine(waitASecond());
		}
		
		private IEnumerator waitASecond()
		{
			yield return new WaitForSeconds(1f);
			
			//Pass back some fake data via a Signal
			fulfillSignal.Dispatch(url);

			networkConnectedSignal.Dispatch (true); // <--------- signal called here and works
		}
                
But if I move the .Dispatch() call, nothing happens in the mediator:
                
                public void Request(string url)
		{
			this.url = url;
			
			MonoBehaviour root = contextView.GetComponent<GameRoot>();
			root.StartCoroutine(waitASecond());

                        networkConnectedSignal.Dispatch (true); // <--------- signal called here and nothing happens
		}
		
		private IEnumerator waitASecond()
		{
			yield return new WaitForSeconds(1f);
			
			//Pass back some fake data via a Signal
			fulfillSignal.Dispatch(url);
		}
                
It seems the only place I can get .Dispatch() to trigger anything is from the coroutine. Also, if I try and .Dispatch() the signal from the StartCommand or any of my own commands, again nothing gets triggered.

I have bound my signal in the context like so:

               injectionBinder.Bind<NetworkConnectedSignal>().ToSingleton();

I inject it where needed like so:

                [Inject]
		public NetworkConnectedSignal networkConnectedSignal{ get; set;}

**Comment by fogAndWhisky** [comment]
Hey @seanachie69, thanks for getting in touch.

That's a great write-up of a problem, which I appreciate. Unfortunately, I'm not able to repro the issue. I've literally copied-and-pasted most of what you wrote into a fresh project, and it all works for me, regardless of where I put the `networkConnectedSignal.Dispatch (true);` line.

Let's establish some baselines so we can hopefully identify the problem:

- While Unity version shouldn't much matter, I'm testing in 5.1.2f1
- I'm using Strange from the tip of the GitHub _master_ branch (commit ba2193f1)
- My code in `ExampleMediator` looks like so:

        [Inject]
        public NetworkConnectedSignal networkConnectedSignal { get; set;}
        public override void OnRegister()
        {
            // Listen out for this Signal to fire
            scoreChangedSignal.AddListener(onScoreChange);
            networkConnectedSignal.AddListener (onNetwork);  // Added this
            // Listen to the view for a Signal
            view.clickSignal.AddListener(onViewClicked);
            view.init ();
        }
    
        public override void OnRemove()
        {
            // Clean up listeners just as you do with EventDispatcher
            scoreChangedSignal.RemoveListener(onScoreChange);
            networkConnectedSignal.RemoveListener (onNetwork);  //Added this
            view.clickSignal.RemoveListener(onViewClicked);
            Debug.Log("Mediator OnRemove");
        }
    
        // Added this handler
        private void onNetwork(bool value)
        {
            Debug.Log ("Network value: " + value);
        }

Perhaps you'll see something different when you look at what I've done...but it all looks good from here.

**Comment by seanachie69** [comment]
Hi @fogAndWhisky,

thanks heaps for getting back to me so quickly :)

I tried the code in a new example project, too ... and it works !? Both projects use the same v0.7 (commit ba2193f) code base. I'm guessing my project isn't set up correctly somewhere along the way. I've gone over all my files and compared the working project to the broken one, but can't see what I'm doing differently/wrong. The only obvious difference is namespace, but I'm assuming that doesn't impact strange, as long as it compiles?

I'm going to try and build up my project again using the working example project as a baseline and cross my fingers!

**Comment by seanachie69** [comment]
It seems the problem was due to where I was calling my code from - the start command. I assume this meant the mediators that were listening weren't ready to receive, yet, even though I set them up first in the start command. Putting the dispatch in a coroutine must allow the mediators to establish themselves, hence that was why it worked there.

**Comment by tomhsmith** [comment]
Experiencing this problem now. Found this useful, but have not setup another signal yet :/
