### ISSUE TITLE
Possible bug in CrossContextInjectionBinder

### ISSUE THREAD

**Issue by leandromperez** [strangeioc/strangeioc#189]
Hello,

I created a small model to explain the problem I found. The model contains 2 interfaces, IVehicle and IEngine. The vehicles have an engine and they can start it. Car, ElectricEngine and GasEngine are concrete classes that implement the corresponding interfaces.

Suppose I want to map IVehicle to Car and have that mapping available in all my contexts. So, in the first, main context, I tell the injection binder to map Car to IVehicle. Then, in the social context I want the engines to be electric, and in the game context, they will use gas:
 
Main Context
			this.injectionBinder.Bind<IVehicle>().To<Car>().CrossContext();

*Note the .CrossContext() message.

Game Context
			this.injectionBinder.Bind<IEngine>().To<ElectricEngine>();

Social Context
			this.injectionBinder.Bind<IEngine>().To<GasEngine>();

Later, In some Game context class I will do this:
this.injectionBinder.GetInstance<IVehicle>().StartEngine();

The Same will happen in other Social context class.

When I try to run, I get this Exception:
InjectionException: Attempt to Instantiate a null binding
		target: strange.examples.multiplecontexts.vehicles.Car
		type: strange.examples.multiplecontexts.vehicles.IEngine

This is due to the fact that the CrossContextInjectionBinder uses the cross context injector, that has no mapping for IEngine.

I think the problem is here:
protected override IInjector GetInjectorForBinding(IInjectionBinding binding)
		{
			//Vehicles. The problem might be here: 
			//The Car binding is Cross-Context. Therefore, it will use the cross context injector, 
			//The Cross-Context injector has no mapping for IEngine.

			if (binding.isCrossContext && CrossContextBinder != null)
			{
				return CrossContextBinder.injector; --> **THIS One has no mapping for IEngine**
			}
			else
			{
				return injector; --> THIS one does Have that mapping.
			}
		}

By simply returning the injector, not the CrossContextBinder.injector, the issue is fixed. But I wonder if it creates undesired side effects.... ?

Any thoughts?
Thanks!

**Comment by WillzZz** [comment]
If you walk through breakpoints does it choose the CC injector here? The IEngine Binding shouldn't be cross context so it should never choose the CC injector.

Assuming you're right it could be a simple fix. We might be accidentally flagging a binding as cross context or (more likely) calling the cross context binder directly when injecting a cross context object.

**Comment by leandromperez** [comment]
Hello,
The IVehicle mapping is Cross Context. So, when GetInjectorForBinding is
called, binding.isCrossContext returns true and the method returns
CrossContextBinder.injector
Then, when instantiating the Car, the same injector tries to resolve
IEngine, which has no mapping, since it's not CC.

*Here you have a stack trace that leads to the moment of choosing the
injector. In which point, binding.isCrossContext returns true.*
strange.extensions.injector.impl.CrossContextInjectionBinder.GetInjectorForBinding
(binding={strange.extensions.injector.impl.InjectionBinding}) in
strangeioc_unity/Assets/StrangeIoC/scripts/strange/extensions/injector/impl/CrossContextInjectionBinder.cs:102
strange.extensions.injector.impl.InjectionBinder.GetInstance
(key={strange.examples.multiplecontexts.vehicles.IVehicle}, name=(null)) in
strangeioc_unity/Assets/StrangeIoC/scripts/strange/extensions/injector/impl/InjectionBinder.cs:60
strange.extensions.injector.impl.InjectionBinder.GetInstance
(key={strange.examples.multiplecontexts.vehicles.IVehicle}) in
strangeioc_unity/Assets/StrangeIoC/scripts/strange/extensions/injector/impl/InjectionBinder.cs:50
strange.extensions.injector.impl.InjectionBinder.GetInstance () in
strangeioc_unity/Assets/StrangeIoC/scripts/strange/extensions/injector/impl/InjectionBinder.cs:71
strange.examples.multiplecontexts.social.CreateUserTileCommand.Execute ()
in
strangeioc_unity/Assets/StrangeIoC/examples/Assets/scripts/multiplecontexts/social/controller/CreateUserTileCommand.cs:58

*Here you have the full stack trace of the exception:*
InjectionException: Attempt to Instantiate a null binding
target: strange.examples.multiplecontexts.vehicles.Car
type: strange.examples.multiplecontexts.vehicles.IEngine
name:
strange.extensions.injector.impl.Injector.failIf (Boolean condition,
System.String message, InjectionExceptionType type, System.Type t,
System.Object name, System.Object target) (at injector/impl/Injector.cs:315)
strange.extensions.injector.impl.Injector.failIf (Boolean condition,
System.String message, InjectionExceptionType type, System.Type t,
System.Object name, System.Object target, System.Reflection.PropertyInfo
propertyInfo) (at injector/impl/Injector.cs:304)
strange.extensions.injector.impl.Injector.getValueInjection (System.Type t,
System.Object name, System.Object target, System.Reflection.PropertyInfo
propertyInfo) (at injector/impl/Injector.cs:225)
strange.extensions.injector.impl.Injector.Instantiate (IInjectionBinding
binding) (at injector/impl/Injector.cs:102)
strange.extensions.injector.impl.InjectionBinder.GetInstance (System.Type
key, System.Object name) (at injector/impl/InjectionBinder.cs:60)
strange.extensions.injector.impl.InjectionBinder.GetInstance (System.Type
key) (at injector/impl/InjectionBinder.cs:50)
strange.extensions.injector.impl.InjectionBinder.GetInstance[IVehicle] ()
(at injector/impl/InjectionBinder.cs:71)
strange.examples.multiplecontexts.social.CreateUserTileCommand.Execute ()
(at
Assets/StrangeIoC/examples/Assets/scripts/multiplecontexts/social/controller/CreateUserTileCommand.cs:58)
strange.extensions.command.impl.CommandBinder.executeCommand (ICommand
command) (at command/impl/CommandBinder.cs:212)
strange.extensions.command.impl.CommandBinder.invokeCommand (System.Type
cmd, ICommandBinding binding, System.Object data, Int32 depth) (at
command/impl/CommandBinder.cs:149)
strange.extensions.command.impl.CommandBinder.next (ICommandBinding
binding, System.Object data, Int32 depth) (at
command/impl/CommandBinder.cs:125)
strange.extensions.command.impl.CommandBinder.ReactTo (System.Object
trigger, System.Object data) (at command/impl/CommandBinder.cs:113)
strange.extensions.command.impl.CommandBinder.Trigger (System.Object key,
System.Object data) (at command/impl/CommandBinder.cs:358)
strange.extensions.dispatcher.eventdispatcher.impl.EventDispatcher.Dispatch
(System.Object eventType, System.Object data) (at
dispatcher/eventdispatcher/impl/EventDispatcher.cs:100)

**Comment by childnode** [comment]
@WillzZz you might have a look at https://github.com/WorldInsight/strangeioc/tree/feature/CrossContext_injection_and_binding

**Comment by WillzZz** [comment]
I fixed this in rc3/tip
