### ISSUE TITLE
Mediator OnRegister not being called

### ISSUE THREAD

**Issue by kencckw** [strangeioc/strangeioc#199]
Unity version: 5.2.1

I have two scenes in my game. 
Main scene load UI scene with LoadLevelAdditive.
The joystickInputMediator work well independently in UI scene but it cannot inject to the gameobject of view in mixed scene.

code:
JoystickInputMediator: http://pastebin.com/e0Gvpg3U
UIBootstrap: http://pastebin.com/xnKrYWiA
UIContext: http://pastebin.com/AfhUdnDY

**Comment by fogAndWhisky** [comment]
This code all looks good to me. The likeliest cause of your problem, I'd imagine, is how you're adding the JoystickView to the hierarchy. Strange wants you to child all GameObjects within the GameObject that holds the Context (UIBootstrap, in this case). When a View Starts, it attempts to find a Context by walking the transform's parent hierarchy. If it finds a Context it will register with it. If it doesn't find a Context (i.e., it encounters `transform.parent == null`), it will make a last-ditch effort to find a Context by going to the first Context that was created (we call this, appropriately enough 'firstContext').

From the symptoms, therefore, I'd guess that your JoystickInputView isn't a child of the GameObject that holds UIBootstrap. When running independently it looks for a Context and can't find one in the hierarchy. So it goes to firstContext...which is UIContext. There's an appropriate binding there, so everything looks good. When you use `LoadLevelAdditive` and attach the UI scene to the Main scene, JoystickView again searches the hierarchy; again it fails and goes to firstContext. This time, however, it finds the MainContext, which has no mapping for JoystickView and so — KAPOW! — the mapping fails.

This is a fundamental way Strange development differs from vanilla Unity development: good housekeeping means that all GameObjects for a Context are children (or children of children, etc) of that Context's GameObject.

Hope that helps!

**Comment by kencckw** [comment]
You are right. Thank you very much
