### ISSUE TITLE
[EDITED] Examples must be fixed ahead of release

### ISSUE THREAD

**Issue by topagae** [strangeioc/strangeioc#201]
Seems to be throwing it when initializing the root context, which I imagine, is not so good. Duplicated instructions as best I could. Very saddening.

InvalidCastException: Cannot cast from source type to destination type.
strange.extensions.command.impl.SignalCommandBinder.ResolveBinding (IBinding binding, System.Object key) (at Assets/StrangeIoC/scripts/strange/extensions/command/impl/SignalCommandBinder.cs:76)
strange.framework.impl.Binder.resolver (IBinding binding) (at Assets/StrangeIoC/scripts/strange/framework/impl/Binder.cs:316)
strange.extensions.command.impl.CommandBinder.resolver (IBinding binding) (at Assets/StrangeIoC/scripts/strange/extensions/command/impl/CommandBinder.cs:374)
strange.framework.impl.Binding.To (System.Object o) (at Assets/StrangeIoC/scripts/strange/framework/impl/Binding.cs:160)
strange.framework.impl.Binding.To[CallWebServiceCommand] () (at Assets/StrangeIoC/scripts/strange/framework/impl/Binding.cs:153)
strange.extensions.command.impl.CommandBinding.To[CallWebServiceCommand] () (at Assets/StrangeIoC/scripts/strange/extensions/command/impl/CommandBinding.cs:91)
strange.examples.myfirstproject.MyFirstContext.mapBindings () (at Assets/StrangeIoC/examples/Assets/scripts/myfirstproject/MyFirstContext.cs:52)
strange.extensions.context.impl.Context.Start () (at Assets/StrangeIoC/scripts/strange/extensions/context/impl/Context.cs:104)
strange.extensions.context.impl.Context..ctor (System.Object view, ContextStartupFlags flags) (at Assets/StrangeIoC/scripts/strange/extensions/context/impl/Context.cs:66)
strange.extensions.context.impl.Context..ctor (System.Object view)
strange.extensions.context.impl.CrossContext..ctor (System.Object view)
strange.extensions.context.impl.MVCSContext..ctor (UnityEngine.MonoBehaviour view)
strange.examples.myfirstproject.MyFirstContext..ctor (UnityEngine.MonoBehaviour view)
strange.examples.myfirstproject.MyFirstProjectRoot.Awake () (at Assets/StrangeIoC/examples/Assets/scripts/myfirstproject/MyFirstProjectRoot.cs:28)

**Comment by fogAndWhisky** [comment]
Hmmm...works just fine for me. There's a weird aspect to your stack trace...it's going through the SignalCommandBinder, which the examples on master shouldn't do. Which branch are you on? (We don't have a 'release' branch...are you on master? On tip?)

**Comment by topagae** [comment]
Master (.07), I spent a while hacking to get it to work with known issues, I so I tried the newest release test branch 1.03f to see if it would work any better. No compilation errors, but when ran I keep getting the above.

**Comment by fogAndWhisky** [comment]
Ah, ok! I see. There's some unfortunate naming of the branch there I guess. 1.03f is a release candidate, not a release (so you're correct...we might do better to rename those branches to 'rc' to avoid confusion). There's still work to do to bring the examples into accord with the latest work, so I'm not surprised at that stack trace.

'master' is the only branch that reflects our current release.

**Comment by topagae** [comment]
S'all good a non-sleep deprived Chris just got master examples working. Going to go through it with a fine tooth comb so I can start my own little mini-project.

**Comment by fogAndWhisky** [comment]
Awesome! I'm going to change the title and leave the issue open, as a reminder to fix all the examples ahead of release.

**Comment by topagae** [comment]
Cool, thanks Marc. Made a few tiny examples a while back with this. Not sure how anyone can do OO without a food IoC library anymore.

**Comment by fogAndWhisky** [comment]
Haha! If I could only get Joachim Ante to agree with that statement! >D

**Comment by topagae** [comment]
Fo reals? That makes me sad in a lot of ways.
