### ISSUE TITLE
Not updated to unity 5 Maybe.

### ISSUE THREAD

**Issue by mitesh504** [strangeioc/strangeioc#210]
When ever I user StrangeIOC which uinity it asks to update APIs and as sometime unity don't updates APIs properly by itself properly.
So should 1 update the scripts or keep them with depricated methods?

**Comment by WillzZz** [comment]
Which version are you using? Everything has been totally up to date for Unity5 for years now.

**Comment by mitesh504** [comment]
@WillzZz , Downloaded from AssetStore https://www.assetstore.unity3d.com/en/#!/content/9267

**Comment by WillzZz** [comment]
Go ahead and pull the latest here either from master, or the soon to be released rc3: release/1.0f3

**Comment by mitesh504** [comment]
Hi, I cloned this Repo and tried copy it to Assets folder but then also same things happened.
At first it gave some errors and warnings to console then I tried to edit a script and updated it to Unity 5 sintex then as returned to Unity as prompt appeared as before (when I was using AssetStore version) asking for updating scripts to Unity 5 APIs so I clicked it "Go Ahead" and Vola all the errors were gone.
