### ISSUE TITLE
SignalMediationBinder NullReferenceException for generic Signals

### ISSUE THREAD

**Issue by AlicanHasirci** [strangeioc/strangeioc#217]
SignalMediationBinder class throws a NullReferenceException on `AssignDelegate` method specifically on `signal.listener.GetType()` part if we try to assign a delegate to a generic signal without a previously existing listener.

You can find my solution on [PR#216](https://github.com/strangeioc/strangeioc/pull/216).

**Comment by WillzZz** [comment]
Took your fix in to my newest RC branch. Closing issue.
