### ISSUE TITLE
Need guidance to develop project in strangeioc

### ISSUE THREAD

**Issue by rajababulukka** [strangeioc/strangeioc#220]
Hi to all..............

I'm interesting to learn strange ioc.... as framework wise i got an idea about it. but while implementing it to my project as beginner , i'm getting confused. 

Can anyone suggest me step by step procedure with sample project.. which consists service, view, mediator, command binder, Inject etc..

Hope for the best........ Waiting for ur suggestions...........

**Comment by WillzZz** [comment]
Hi! Welcome to Strange! We have a variety of places you can learn about strange.

First and foremost, these sort of questions belong on the [google group](https://groups.google.com/forum/?hl=en#!forum/strangeioc). We have a community of devs there who can help answer your questions.

Next, we have a slightly old but still useful project that was created when strange was initially released called [strange rocks] (https://github.com/strangeioc/strangerocks) so take a look at that, as well. Hope that helps!

**Comment by rajababulukka** [comment]
Thanks u so much for quick response.....
