### ISSUE TITLE
Bindings/Mediators not being properly setup when multiple contexts are active

### ISSUE THREAD

**Issue by jwvanderbeck** [strangeioc/strangeioc#238]
Sample skeleton project exhibiting this issue, made with Unity 5.6.  This sample project is bare bones and uses no assets beyond Strange itself.  That code from Strange is included in the project.
https://dl.dropboxusercontent.com/u/1522737/Strange%20Multiple%20Contexts.zip

To reproduce:
1. Open the scene "Menu" and play in editor
2. Note in the log the sequence of events, especially noting that the Mediator's OnRegister is called as expected.
3. Click the button, and note that the signal and command happen.
4. Stop Play in Editor and load the "Root" scene
5. Play in editor.  This scene will additively load the Menu scene, so there are now two contexts in play, Root and Menu
6. Note in the log that the Menu context does not properly get its mediator setup, even though the mapBindings runs.  Also note the Injection error.
7. Click the button and notice NRE happens because the binding never got set up.

As seen in this example project, when only the Menu context is active it runs fine and works as expected.  The mediator is set up and registered, and the signal is injected fine, and the command runs when the button is clocked.

However when the Root context loads the Menu context, setting a scene where both the Root and Menu context are active, the Menu Context fails to be properly setup.  The mediator is never registered, and the signal fails to bind.

**Comment by jwvanderbeck** [comment]
Note that the Strange IoC code included in the project is from the 1.0f5 branch, and has been modified in only one way: The code in InjectAttribute.cs has been namespaced so as to not pollute the global namespace, and usings were added were necessary based on this change.  I posted about this here: https://groups.google.com/forum/#!topic/strangeioc/-I9mS9G5bwQ , and the thought was that this should be fine to do.  That said I am going to try and reproduce this issue with clean Strange code to see if it still occurs.

**Comment by jwvanderbeck** [comment]
Ok I have confirmed the issue still exists with a clean checkout of 1.0f5.

**Comment by WillzZz** [comment]
Your view is not a child of your context, therefore it's seeking out the Context.firstContext and not finding the mediation or signal binding. i'll comment on the google group, as well.

**Comment by jwvanderbeck** [comment]
Child? As in physically in the scene hierarchy?

**Comment by WillzZz** [comment]
Yup. That's a core requirement of the context/view/mediation system.

**Comment by jwvanderbeck** [comment]
And I guess the event context wasn't getting setup because Strange failed to recover cleanly after the Mediator issue?

**Comment by WillzZz** [comment]
Well it wasn't mediating the view and it was searching for a context wherever it could find it, so it defaulted to Context.firstContext, which in this case is RootContext. Which did not have the binding you needed
