### ISSUE TITLE
InvalidCastException in TestView / Do examples need update to Unity 2017.x?

### ISSUE THREAD

**Issue by MrShadowGames** [strangeioc/strangeioc#241]
Greetings guys!

After packing tons of managers and wiring them with all the unity game objects I found myself struggling with maintaining all the spaghetti and when changing any manager the events in the inspectors go poof! Even the most naive developer recognizes that such an approach cannot be the way to scale up any Unity project on the long term.

So, I was looking around for something that would provide dependency injection or something even better and I found StrangeIoC. Your framework seems very promising and I do hope StrangeIoC can help me to properly refactor and separate my manager scripts from the many game components.

However, after checking out the git project I saw that the last commit was in February 2017.
Anyway, I tried out the TestView example in Unity 2017.2.0f3 and it seems to not be working anymore. 

```
	public class MyFirstProjectRoot : ContextView
	{
	
		void Awake()
		{
			//Instantiate the context, passing it this instance.
			context = new MyFirstContext(this);

			//This is the most basic of startup choices, and probably the most common.
			//You can also opt to pass in ContextStartFlag options, such as:
			//
			//context = new MyFirstContext(this, ContextStartupFlags.MANUAL_MAPPING);
			//context = new MyFirstContext(this, ContextStartupFlags.MANUAL_MAPPING | ContextStartupFlags.MANUAL_LAUNCH);
			//
			//These flags allow you, when necessary, to interrupt the startup sequence.
		}
	}
```

The construction of that context throws an InvalidCastException as in the stacktrace given below.

So my question is: Is the project dead or do the examples need an update for Unity 2017.x?

Oh, and on a side note: Why are you guys not setting up a patreon account or something? It looks like you've put in some real hard work in all this, and I'm not wondering at all when the authors of libraries/frameworks loose interest because keeping up a source project is time and energy consuming. Anyway, just my thoughts. :)

Best regards,
Shadow

---
Stacktrace:
`ork/impl/Binder.cs:316)
strange.extensions.command.impl.CommandBinder.resolver (strange.framework.api.IBinding binding) (at Assets/StrangeIoC/scripts/strange/extensions/command/impl/CommandBinder.cs:374)
strange.framework.impl.Binding.To (System.Object o) (at Assets/StrangeIoC/scripts/strange/framework/impl/Binding.cs:160)
strange.framework.impl.Binding.To[T] () (at Assets/StrangeIoC/scripts/strange/framework/impl/Binding.cs:153)
strange.extensions.command.impl.CommandBinding.To[T] () (at Assets/StrangeIoC/scripts/strange/extensions/command/impl/CommandBinding.cs:91)
strange.examples.myfirstproject.MyFirstContext.mapBindings () (at Assets/StrangeIoC/examples/Assets/scripts/myfirstproject/MyFirstContext.cs:52)
strange.extensions.context.impl.Context.Start () (at Assets/StrangeIoC/scripts/strange/extensions/context/impl/Context.cs:104)
strange.extensions.context.impl.Context..ctor (System.Object view, strange.extensions.context.api.ContextStartupFlags flags) (at Assets/StrangeIoC/scripts/strange/extensions/context/impl/Context.cs:66)
strange.extensions.context.impl.Context..ctor (System.Object view) (at Assets/StrangeIoC/scripts/strange/extensions/context/impl/Context.cs:70)
strange.extensions.context.impl.CrossContext..ctor (System.Object view) (at Assets/StrangeIoC/scripts/strange/extensions/context/impl/CrossContext.cs:65)
strange.extensions.context.impl.MVCSContext..ctor (UnityEngine.MonoBehaviour view) (at Assets/StrangeIoC/scripts/strange/extensions/context/impl/MVCSContext.cs:206)
strange.examples.myfirstproject.MyFirstContext..ctor (UnityEngine.MonoBehaviour view) (at Assets/StrangeIoC/examples/Assets/scripts/myfirstproject/MyFirstContext.cs:29)
strange.examples.myfirstproject.MyFirstProjectRoot.Awake () (at Assets/StrangeIoC/examples/Assets/scripts/myfirstproject/MyFirstProjectRoot.cs:28)
`

**Comment by WillzZz** [comment]
Hello! Were you using master or a release branch?  There's not many recent commits because a) I have very little free time and b) there aren't a whole lot of meaningful changes to be made to the framework! It's very possible we have some demo issues in the latest versions of Unity, although this one is rather surprising. The good news is I think I'll be merging everything to master after I confirm everything works in 2017.2

**Comment by WillzZz** [comment]
Alright. Found the problem. This is a side effect of an older update which defaulted to Signals. I'll update the example.

**Comment by CreativeWarlock** [comment]
Most excellent, thanks WillzZz!

I tried the TestView out from the 1.05f release, but tried also from the master. Both with the same result.

Thanks for looking into this!
