### ISSUE TITLE
Regarding Future Developement

### ISSUE THREAD

**Issue by rajanukala514** [strangeioc/strangeioc#246]
Hello developer, We are decided to use strange for our big project. Is it works with all unity versions? is it works in ios build without any issues? We know its very well works for android. Pls give us suggestion. thanks

**Comment by WillzZz** [comment]
Strange should have no issues in any version of unity and definitely not on iOS. Please take similar questions to the google group. This isn't really the place for this sort of question. Closing.  Thank you, and best of luck!
