### ISSUE TITLE
Some Mediators not being created while others are

### ISSUE THREAD

**Issue by RisingSunStudios** [strangeioc/strangeioc#249]
Hi all,

Firstly, I really enjoy using StrangeIOC! I'm having a weird issue. I have a heirachy like so:

- ContextView
-- Canvas
--- Menu A - (MenuAView, MenuAMediator)
--- Menu B - (MenuBView, MenuBMediator)
--- Menu C - (MenuCView, MenuCMediator)

ContextView is the root ContextView. Menu A, B and C all have unique views and mediators. I have attached the View script in the editor, and the Context is binding all three assigning mediators to the appropriate views.

When I run the game, only Menu A and Menu C have mediators attached.
This is a very simple example, but I've checked the obvious things - child of the context GO, no typos in the mediatin binding etc..

Any suggestions?

I'm using the latest code with Unity 2019

edit - could it be related to the fact that I'm loading the scene additively, and a timing issue is causing the objects to not exist when the mediation binder is doing its thing?

**Comment by WillzZz** [comment]
Additive loads should work fine. Everything should be serialized, so there shouldn't be any race/timings issues.

Typically mediators not getting registered is one of a few things:

- Overriding Awake or Start in the view without calling base.Awake/Start
- A View not being within the Hierarchy of the Context
- Script execution order for views being higher priority than the context.

Everything else might be game specific, but mediation is pretty simple.

**Comment by RisingSunStudios** [comment]
Thanks for the reply. I had this issue happening with 3 new views, no overrides of Awake or Start and ensuring the View was within the heirachy of the context. I didn't check the script execution order though, that may be the culprit!

It worked perfectly fine adding the Views at runtime instead of via the editor, so I'll close this ticket and if it occurs in the future I'll make a mental note to check the script execution order.

Cheers,
