### ISSUE TITLE
Oculus Go compitability

### ISSUE THREAD

**Issue by marad747** [strangeioc/strangeioc#250]
Doest it compitability with oculus go?

**Comment by WillzZz** [comment]
I've not tried (I don't own a headset), but nothing inherently prevents its use. I would be very careful and ensure you're pooling and avoiding any potential command/signal overhead issues with main loop code. Using it as communication for your UI layer in a VR app would probably work great. Do you have any specific concerns or reason to think it would not work properly?

**Comment by marad747** [comment]
all fine( seems that)
