### ISSUE TITLE
Crash when injecting a model inside a model

### ISSUE THREAD

**Issue by tattyd** [strangeioc/strangeioc#256]
Hi,

Using the 'myfirstproject' example...

Add a new interface IAnotherModel.cs, as well as the implementation AnotherModel.cs:

```
using System;

namespace strange.examples.myfirstproject
{
	public interface IAnotherModel
	{
		string data{get;set;}
	}
}
```

```
/// Example Model
/// ======================
/// Nothing to see here. Just your typical place to store some data.

using System;
using UnityEngine;

namespace strange.examples.myfirstproject
{
	public class AnotherModel : IAnotherModel
	{
		public string data {get;set;}

        [Inject]
        public IExampleModel exampleModel {get;set;}
		
		public AnotherModel ()
		{
            Debug.Log("Another model!" + exampleModel.ToString());
		}
	}
}
```

Then, add a Binding:

```
		protected override void mapBindings()
		{
			//Injection binding.
			//Map a mock model and a mock service, both as Singletons
			injectionBinder.Bind<IExampleModel>().To<ExampleModel>().ToSingleton();
			injectionBinder.Bind<IAnotherModel>().To<AnotherModel>().ToSingleton();
			injectionBinder.Bind<IExampleService>().To<ExampleService>().ToSingleton();
			.....
```

Now, somewhere that will get executed, for example in StartCommand, Inject an instance of IAnotherModel (which, in turn should inject an instance of ExampleModel and print it to the console)

```
	public class StartCommand : EventCommand
	{
		
		[Inject(ContextKeys.CONTEXT_VIEW)]
		public GameObject contextView{get;set;}

		[Inject]
		public IAnotherModel model {get;set;}
		.....
```

I get the following crash: ArgumentException: Object of type 'System.RuntimeType' cannot be converted to type 'strange.examples.myfirstproject.IAnotherModel'.

Which seems nonsensical. Problems go away when you remove the [Inject] IExampleModel from IAnotherModel. Any ideas?

**Comment by fogAndWhisky** [comment]
`public class AnotherModel : IAnotherModel `

You're extending where you should be implementing. Hope that helps!

**Comment by tattyd** [comment]
Oh man, that's a real shamecube.gif moment! I will try that tomorrow.

FWIW, my code runs just fine as long as I don't try to access the injected field in the constructor. So my latest hypothesis (until your reply) was that accessing injected fields in constructors was no bueno.

Also -- just checking -- in the Strange examples, all of the models there extend (vs implement) their respective interface. Is that a bug in the example code or intentional there?

Thanks for the help :)

**Comment by tattyd** [comment]
Actually, bear with me as I'm a Java developer at heart here :) Could you explain how to differentiate extending vs implementing when both are accomplished with the : operator?

**Comment by fogAndWhisky** [comment]
Oh dear. I think I get the shame cube. It's been many years since I coded regularly. I misidentified the issue. You are indeed correctly implementing.

I think your second idea is closer to the mark. Accessing a field during construction is more likely the problem. If memory serves, we allow for a [PostConstruct] tag to handle this sort of situation. That method will trigger immediately after injection.

**Comment by tattyd** [comment]
Aha, that's exactly what i was looking for! Thanks!

I knew I'd seen something like this before, but was mistakenly thinking of onRegister (which only mediators get). [PostConstruct] seems like it'll do the trick.

I guess there's still a potential FR here for a more descriptive error message, but based on your reply it seems like you won't be in a position to fix it soon ;)

Thanks again!
