### ISSUE TITLE
Injections is not set while constructing

### ISSUE THREAD

**Issue by oistikbal** [strangeioc/strangeioc#257]
Inside constructor, calling calling any injection will throw error. Need delay to get injections  or will get errors.
The example code which produce errors.

        [Inject(ContextKeys.CONTEXT_VIEW)]
        public GameObject ContextView { get; set; }

        public ExampleService() 
        {
            Debug.Log(ContextView.name);
        }

**Comment by fogAndWhisky** [comment]
Injection is not permitted inside constructors. Leverage the
[PostConstruct] feature to manage injections for this case.

**Comment by oistikbal** [comment]
Yes, i noticed that after posting this sadly.
