### ISSUE TITLE
Request: commandBinder.Execute<MyCommand>();

### ISSUE THREAD

**Issue by ghost** [strangeioc/strangeioc#55]
1- PROBLEM

I would like to call a command (with injections inside) directly. An example I believe is architecturally sound is for a Command to arbitrarily call another Command directly.

My first attempt fails (because the injections inside);
new LoadButtonClickCommand().Execute();

2- SAMPLE SOLUTION
Per twitter @StrangeIoC offered this. It fails for the reasons given. A similar alternative would be acceptable for my needs. Something more terse would be better.

//LINE 160 BELOW
injectionBinder.Bind<ICommand>().To (typeof (LoadButtonClickCommand));

//LINE 162 BELOW
ICommand command = injectionBinder.GetInstance<ICommand>() as ICommand;

command.data = null;
command.Execute();
injectionBinder.Unbind<ICommand>();

// COMPILER ERROR ON LINE 162
// InjectionException: Attempt to Instantiate a null binding.
//      target: com.rmc.projects.strangeioc_template.mvc.controller.commands.LoadButtonClickCommand
//      type: com.rmc.projects.strangeioc_template.IService
//      name: 

3- MY PROPOSAL
With only my beginner's view of Strange, I recommend;

commandBinder.Execute< LoadButtonClickCommand >();

And this would not interfere-with/require-that any of that commands other existing bindings (e.g. signal-to-command binding)

**Comment by lovedluck** [comment]
> According to the error, you forgot to map a dependency to IService. If you fix that binding, the code you got via Twitter should work.
> 
> As I mentioned to you there, I'm dubious about the architectural soundness of this case, when you could use Events or Signals and maintain decoupling. I'll consider this, though, discuss it with the others who help me maintain Strange, and let you know what we reckon.
> 
> In the meantime, there's no reason you couldn't implement the Next<T> method (provided you clean up your bindings) and do what you want regardless of my advice on the matter. :)

Thanks for your advice, really useful to me.
