### ISSUE TITLE
"Live bindings"

### ISSUE THREAD

**Issue by srimarc** [strangeioc/strangeioc#63]
@rfish Requested a way to update injections on-the-fly.

**Use case**
I have a binding. Say:

    injectionBinder.Bind<ISocialService>().To<FacebookService>().ToSingleton();

If I toggle the service at runtime, I can do this:

    injectionBinder.Unbind<ISocialService>();
    injectionBinder.Bind<ISocialService>().To<TwitterService>().ToSingleton();

This works for all **future** injections, but what about places I've already injected? I'd like to be able to "live update" a pre-existing binding.

**Proposal**
The developer will mark a binding for live update:

    injectionBinder.Bind<ISocialService>().To<FacebookService>().ToSingleton().Live();

The InjectionBinder (or the Injector itself) will track those marked bindings in a dictionary...

    //key is the binding key. value is the target instance
    Dictionary<object, WeakReference<object>>

...such that whenever the binding is rebound, the target instance is re-injected with the updated value.

**Comment by fogAndWhisky** [comment]
This was an idea I had some time ago that met with middling support, so I'm closing for now. Anyone who still thinks this is a good idea and wants us to re-consider it can comment and argue for re-opening if they want.
