### ISSUE TITLE
Demo fails since injection does not take place

### ISSUE THREAD

**Issue by JakobRasmussen** [strangeioc/strangeioc#84]
Hi,

In the multiple context demo, the following is the init logic of the ShipView

```
gameObject.AddComponent<ClickDetector>();
ClickDetector clicker = gameObject.GetComponent<ClickDetector>();
clicker.dispatcher.AddListener(ClickDetector.CLICK, onClick);
```

However clicker.dispatcher is null, which makes sense as neither AddComponent or GetComponent would know how to inject the ClickDetector.

For some reason the same code works in the MyFirstProject example, which suggests this is some sort of timing issue, which is clearly not optimal.

**Comment by orbenozio** [comment]
WillzZz, can you provide a solution for this issue, It still occurs. 
Thanks.

**Comment by srimarc** [comment]
I've never experienced this issue. Since the ClickDetector doesnt rely on injection, the OP's suggestion that it is something to do with injection doesn't really make sense. Could you provide some specifics of your case? Which version of Strange? Which version of Unity? Platform? Anything else that might help us repro this?

**Comment by orbenozio** [comment]
* I'm using Unity 4.5.3
* Took the code yesterday from the asset store (Lateset version).
* The error is: NullReferenceException: Object reference not set to an instance of an object
strange.examples.multiplecontexts.game.ShipView.init () (at Assets/StrangeIoC/examples/Assets/scripts/multiplecontexts/game/view/ShipView.cs:40)
* This occurs for both ShipView and EnemyView.
* OS: Windows 8.1 Pro

=========
1. I imported the files into Unity.
2. Opened the main scene (under "multiplecontexts" folder)
3. Run it,
4. The above exception appears.

**Comment by unitymarc** [comment]
Cool. Could you try the following things? First, make sure when you run the MultipleContext demo that you open the Build Settings and add the relevant scenes? If that doesn't fix it, please download the latest version of Strange from master? Our version in the App Store is out-of-date...we've been meaning to update it, but the process is cumbersome, and we've been hard at work trying to get v1 out the door.

**Comment by orbenozio** [comment]
Sorry, forgot to mention that I added the scenes to the build settings. 

I imported the Master version into Unity, however there is only dev_test_scene.unity
and not the game scene. 

Any suggestions?

**Comment by unitymarc** [comment]
Your last comment is a bit of a mystery to me. dev_test_scene.unity? If you look here:

https://github.com/strangeioc/strangeioc/tree/master/StrangeIoC/examples/Assets/scenes/multiplecontexts

You'll see that multiplecontexts has three scenes: game, main and social. Would you mind trying again? I wan to isolate this as tightly as possible so we can figure out what if anything is amiss. Thanks!

**Comment by orbenozio** [comment]
OK, Thanks, 
I opened the strange-unity folder. 

I follow your steps and it works just fine.
Thank you.

**Comment by srimarc** [comment]
Cool!
