### ISSUE TITLE
InjectionException: Expecting [PropertyType] value but got 'MonoType'

### ISSUE THREAD

**Issue by yourpalmark** [strangeioc/strangeioc#93]
Any reason why I would be getting this?
It is related to one particular injection, if I remove it I no longer get the error, but also it is very similar to other injections in that there is nothing odd about it. Not that I'm seeing.
Is there any light you might be able to shed on MonoType and why the injection would be getting that?

It only happens on iOS device, not in editor.

**Comment by fogAndWhisky** [comment]
Is this still an issue? I'm closing this, since it's so old. @yourpalmark please re-open if you want us to investigate.
