### ISSUE TITLE
new httpConnection() in a singleton service!?

### ISSUE THREAD

**Issue by sorob** [strangeioc/strangeioc#98]
Hi,

I'm having a hard time making this to work : 
1- I bind a service as a singleton ! 
            injectionBinder.Bind<ISocketService>().To<SocketService>().ToSingleton();
2- now I need to setup a connection to request something from web :+1: 

public SocketService ()
		{
            client = new Client(url);
}

3 - I get an error : 
ArgumentException: failed to convert parameters
System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at /Users/builduser/buildslave/monoAndRuntimeClassLibs/build/mcs/class/corlib/System.Reflection/MonoMethod.cs:192)

** I think this is caused by IoC trying to instantiate a non-static class inside a static (singleton) class ! 

how do we get around this?

**Comment by fogAndWhisky** [comment]
Old. Closing. Feel free to re-open if there's more to discuss.
